D2: false
adam: true
batch_size: 16
bg: true
channel: 6
class_num: 751
cluster: xyzrgb
conv: EdgeConv
dataset_path: ./2DMarket/
drop_connect_rate: 0.0
droprate: 0.7
efficient: true
erase: 0.0
feature_dims:
- 48
- 96
- 96
- 192
- 192
- 384
- 384
final_bn: false
flip: true
gpu_ids:
- 0
id_skip: 2
init_points: 768
jitter: false
k: 9
labelsmooth: false
layer_drop: 0
light: false
load_model_path: ''
lrRate: 0.00035
name: Efficient_ALL_2SDDense_b16_lr3.5_flip_slim0.5_warm10_scale_e0_d7+bg_adam_init768_clusterXYZRGB_e500_id2_bn_k9_conv2
no_se: false
no_xyz: false
norm: false
norm_layer: bn
npart: 1
num_conv: 2
num_epochs: 500
num_workers: 2
pre_act: false
pretrained_name: None
res_scale: 1.0
resume: false
rotate: false
scale: true
slim: 0.5
step: false
stride: 2
train_all: true
use2: false
use_DGCNN: false
use_MSG: false
use_SSG: false
use_dense: true
use_dense2: false
warm_epoch: 10
