D2: false
adam: true
batch_size: 16
bg: true
channel: 6
class_num: 767
cluster: xyzrgb
conv: EdgeConv
dataset_path: 2DCUHK
drop_connect_rate: 0.0
droprate: 0.7
efficient: true
erase: 0.0
feature_dims:
- 48
- 96
- 192
- 384
final_bn: false
flip: true
gpu_ids:
- 0
id_skip: false
init_points: 768
jitter: false
k: 20
labelsmooth: false
layer_drop: 0
light: false
load_model_path: ''
lrRate: 0.0004
name: Efficient_CUHK_ALL_SDense_b16_lr4_flip_slim0.5_warm10_scale_e0_d7+bg_adam_init768_clusterXYZRGB_e1000
no_se: false
no_xyz: false
norm: false
norm_layer: bn
npart: 1
num_conv: 1
num_epochs: 1000
num_workers: 2
pre_act: false
pretrained_name: None
res_scale: 1.0
resume: false
rotate: false
scale: true
slim: 0.5
step: false
stride: 2
train_all: true
use2: false
use_DGCNN: false
use_MSG: false
use_SSG: false
use_dense: true
use_dense2: false
warm_epoch: 10
