D2: false
adam: true
balance: true
batch_size: 16
bg: true
channel: 6
class_num: 1041
cluster: xyzrgb
conv: EdgeConv
dataset_path: 2DMSMT
drop_connect_rate: 0.0
droprate: 0.7
efficient: true
erase: 0.0
feature_dims:
- 64
- 128
- 256
- 512
final_bn: false
flip: true
gpu_ids:
- 0
id_skip: 0
init_points: 768
jitter: false
k: 20
labelsmooth: false
layer_drop: 0
light: false
load_model_path: ''
lrRate: 0.0003
name: Efficient_MSMT_ALL_Dense_b16_lr3_flip_slim0.5_warm10_scale_e0_d7+bg_adam_init768_clusterXYZRGB_e800_wa0.9_balance
no_se: false
no_xyz: false
norm: false
norm_layer: bn
npart: 1
num_conv: 1
num_epochs: 800
num_workers: 2
pre_act: false
pretrained_name: None
res_scale: 1.0
resume: false
rotate: false
scale: true
shuffle: -1
slim: 0.5
step: false
stride: 2
sync_bn: false
train_all: true
use2: false
use_DGCNN: false
use_MSG: false
use_SSG: false
use_dense: true
use_dense2: false
wa: true
wa_start: 0.9
warm_epoch: 10
