ASPP: 0
D2: false
adam: true
adamW: false
amsgrad: true
balance: false
batch_size: 36
bg: true
cg: false
channel: 6
circle: false
class_num: 751
class_sampler: 3
cluster: xyzrgb
conv: EdgeConv
dataset_path: ./2DMarket/
drop_connect_rate: 0.0
droprate: 0.7
efficient: true
erase: 0.0
feature_dims:
- 64
- 128
- 256
- 512
final_bn: false
flip: true
fp16: false
gamma: 32
gem: true
gpu_ids:
- 0
id_skip: 0
init_points: 768
jitter: false
k: 20
labelsmooth: false
layer_drop: 0
light: false
load_model_path: ''
lookahead: false
lrRate: 0.001
name: Efficient_ALL_Dense_b36_lr10_flip_slim0.5_warm10_scale_e0_d7+bg_adam_init768_clusterXYZRGB_e1500_wa0.9_GeM_bn2_class3_amsgrad
nce: false
no_fnorm: false
no_se: false
no_xyz: false
norm: false
norm_layer: bn2
npart: 1
num_conv: 1
num_epochs: 1500
num_workers: 2
pre_act: false
pretrained_name: None
res_scale: 1.0
restart: false
resume: false
rotate: false
sam: false
scale: true
shuffle: -1
slim: 0.5
step: false
stride: 2
sync_bn: false
train_all: true
twins: false
use2: false
use_DGCNN: false
use_MSG: false
use_SSG: false
use_dense: true
use_dense2: false
wa: true
wa_start: 0.9
warm_epoch: 10
warm_iteration: 3590
warm_up: 0.1
wd: 0.0005
