ASPP: 0
D2: false
adam: true
adamW: false
amsgrad: true
balance: true
batch_size: 36
bg: true
cg: false
channel: 6
circle: true
class_num: 702
class_sampler: 0
cluster: xyzrgb
conv: EdgeConv
dataset_path: 2DDuke
drop_connect_rate: 0.0
droprate: 0.7
efficient: true
erase: 0.0
feature_dims:
- 48
- 96
- 96
- 192
- 192
- 384
- 384
final_bn: false
flip: true
fp16: false
gamma: 64.0
gem: true
gpu_ids:
- 0
id_skip: 2
init_points: 768
jitter: false
k: 9
labelsmooth: false
layer_drop: 0
light: false
load_model_path: ''
lookahead: false
lrRate: 0.0006
name: Duke_Efficient_ALL_2SDDense_b36_lr6_flip_slim0.5_warm10_scale_e0_d7+bg_adam_init768_clusterXYZRGB_e1000_id2_bn_k9_conv2_balance
nce: false
no_fnorm: false
no_se: false
no_xyz: false
norm: false
norm_layer: bn2
npart: 1
num_conv: 2
num_epochs: 1000
num_workers: 2
pre_act: false
pretrained_name: None
res_scale: 1.0
restart: false
resume: false
rotate: false
sam: false
scale: true
shuffle: -1
slim: 0.5
step: false
stride: 2
sync_bn: false
train_all: true
twins: false
use2: false
use_DGCNN: false
use_MSG: false
use_SSG: false
use_dense: true
use_dense2: false
wa: false
wa_start: 0.9
warm_epoch: 10
warm_iteration: 4590
warm_up: 0.1
wd: 0.0005
